/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.uefs.ecomp.bazar.view;

import java.awt.CardLayout;

import br.uefs.ecomp.bazar.model.ControllerBazar;
import br.uefs.ecomp.bazar.model.Leilao;
import br.uefs.ecomp.bazar.model.Produto;
import br.uefs.ecomp.bazar.model.exception.LeilaoNaoCadastrouException;

import br.uefs.ecomp.bazar.model.exception.LoginFalhouException;
import br.uefs.ecomp.bazar.model.exception.ProdutoNaoCadastrouException;
import br.uefs.ecomp.bazar.model.exception.UsuarioNaoCadastrouException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

public class TelaPrincipal extends javax.swing.JFrame {
    
    private ControllerBazar cb = new ControllerBazar();
    private TelaLogin telaLogin = new TelaLogin();
    private int optLeilao;
    private Leilao leilao;
    private Produto produto;
    
    public TelaPrincipal() {
        initComponents();
        
        this.cb = telaLogin.getCb();
        
        btnHorario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NaveBar = new javax.swing.JPanel();
        btnVender = new javax.swing.JButton();
        btnLeiloes = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        JMain = new javax.swing.JPanel();
        JMeusLeiloes = new javax.swing.JPanel();
        JVender = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCadastrarProduto = new javax.swing.JButton();
        cmbLeilao = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPreco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblIncremento = new javax.swing.JTextField();
        txtProduto = new javax.swing.JLabel();
        btnCadastrarLeilao = new javax.swing.JButton();
        btnHorario = new javax.swing.JButton();
        JComprar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leilão");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 200));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("L e i l ã o");

        NaveBar.setBackground(new java.awt.Color(204, 204, 204));

        btnVender.setBackground(new java.awt.Color(204, 204, 204));
        btnVender.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        btnVender.setForeground(new java.awt.Color(0, 0, 0));
        btnVender.setText("Quero Vender");
        btnVender.setBorderPainted(false);
        btnVender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVender.setOpaque(true);
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        btnLeiloes.setBackground(new java.awt.Color(204, 204, 204));
        btnLeiloes.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        btnLeiloes.setForeground(new java.awt.Color(0, 0, 0));
        btnLeiloes.setText("Meus Leilões");
        btnLeiloes.setBorderPainted(false);
        btnLeiloes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLeiloes.setOpaque(true);
        btnLeiloes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeiloesActionPerformed(evt);
            }
        });

        btnComprar.setBackground(new java.awt.Color(204, 204, 204));
        btnComprar.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        btnComprar.setForeground(new java.awt.Color(0, 0, 0));
        btnComprar.setText("Quero Comprar");
        btnComprar.setBorderPainted(false);
        btnComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnComprar.setOpaque(true);
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(204, 204, 204));
        btnSair.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        btnSair.setForeground(new java.awt.Color(0, 0, 0));
        btnSair.setText("Sair");
        btnSair.setBorderPainted(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSair.setOpaque(true);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NaveBarLayout = new javax.swing.GroupLayout(NaveBar);
        NaveBar.setLayout(NaveBarLayout);
        NaveBarLayout.setHorizontalGroup(
            NaveBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NaveBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLeiloes)
                .addGap(20, 20, 20)
                .addComponent(btnVender)
                .addGap(20, 20, 20)
                .addComponent(btnComprar)
                .addGap(20, 20, 20)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NaveBarLayout.setVerticalGroup(
            NaveBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NaveBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NaveBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVender)
                    .addComponent(btnComprar)
                    .addComponent(btnLeiloes)
                    .addComponent(btnSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JMain.setBackground(new java.awt.Color(205, 205, 205));
        JMain.setLayout(new java.awt.CardLayout());

        JMeusLeiloes.setBackground(new java.awt.Color(205, 205, 205));

        javax.swing.GroupLayout JMeusLeiloesLayout = new javax.swing.GroupLayout(JMeusLeiloes);
        JMeusLeiloes.setLayout(JMeusLeiloesLayout);
        JMeusLeiloesLayout.setHorizontalGroup(
            JMeusLeiloesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        JMeusLeiloesLayout.setVerticalGroup(
            JMeusLeiloesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        JMain.add(JMeusLeiloes, "meusLeioes");

        JVender.setBackground(new java.awt.Color(205, 205, 205));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("Cadastrar Leilão:");

        btnCadastrarProduto.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        btnCadastrarProduto.setText("Cadastrar Produto");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        cmbLeilao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha seu leilão", "Manual", "Automatico", "Automatico Fechado" }));
        cmbLeilao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLeilaoItemStateChanged(evt);
            }
        });
        cmbLeilao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLeilaoActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tipo de Leilão:");

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Produto:");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Preço:");

        lblPreco.setBackground(new java.awt.Color(255, 255, 255));
        lblPreco.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblPreco.setForeground(new java.awt.Color(30, 30, 30));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Incremento Minimo:");

        lblIncremento.setBackground(new java.awt.Color(255, 255, 255));
        lblIncremento.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblIncremento.setForeground(new java.awt.Color(30, 30, 30));
        lblIncremento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblIncrementoActionPerformed(evt);
            }
        });

        txtProduto.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        btnCadastrarLeilao.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        btnCadastrarLeilao.setText("Cadastrar Leilão!");
        btnCadastrarLeilao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarLeilaoActionPerformed(evt);
            }
        });

        btnHorario.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnHorario.setText("Definir horário");
        btnHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JVenderLayout = new javax.swing.GroupLayout(JVender);
        JVender.setLayout(JVenderLayout);
        JVenderLayout.setHorizontalGroup(
            JVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JVenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JVenderLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(JVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JVenderLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JVenderLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cmbLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(120, 120, 120))
                    .addGroup(JVenderLayout.createSequentialGroup()
                        .addGroup(JVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCadastrarLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JVenderLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lblIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JVenderLayout.createSequentialGroup()
                        .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JVenderLayout.setVerticalGroup(
            JVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JVenderLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(JVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHorario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(JVenderLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnCadastrarLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        JMain.add(JVender, "vender");

        JComprar.setBackground(new java.awt.Color(205, 205, 205));
        JComprar.setPreferredSize(new java.awt.Dimension(694, 372));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 30, 30));
        jLabel7.setText("Pesquise aqui:");

        txtBusca.setBackground(new java.awt.Color(255, 255, 255));
        txtBusca.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtBusca.setForeground(new java.awt.Color(0, 0, 0));

        btnBuscar.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");

        javax.swing.GroupLayout JComprarLayout = new javax.swing.GroupLayout(JComprar);
        JComprar.setLayout(JComprarLayout);
        JComprarLayout.setHorizontalGroup(
            JComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JComprarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        JComprarLayout.setVerticalGroup(
            JComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JComprarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(JComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(322, Short.MAX_VALUE))
        );

        JMain.add(JComprar, "comprar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NaveBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(JMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NaveBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(JMain, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        // TODO add your handling code here:
        CardLayout cardVender = (CardLayout) JMain.getLayout();
        cardVender.show(JMain, "vender");
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnLeiloesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeiloesActionPerformed
        // TODO add your handling code here:
        CardLayout cardLeilões = (CardLayout) JMain.getLayout();
        cardLeilões.show(JMain, "meusLeioes");
    }//GEN-LAST:event_btnLeiloesActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        CardLayout cardComprar = (CardLayout) JMain.getLayout();
        cardComprar.show(JMain, "comprar");
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        cb.deslogar();
        this.dispose();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void cmbLeilaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLeilaoActionPerformed
        // TODO add your handling code here:
        int leilaoSelecionado = cmbLeilao.getSelectedIndex();
        this.optLeilao = leilaoSelecionado;
        if(leilaoSelecionado == 2 || leilaoSelecionado == 3){
            btnHorario.setVisible(true);
        } else {
            btnHorario.setVisible(false);
        }
    }//GEN-LAST:event_cmbLeilaoActionPerformed

    private void cmbLeilaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLeilaoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLeilaoItemStateChanged

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        TelaCadastroProdutoModal telaProduto = new TelaCadastroProdutoModal(this, true);
        telaProduto.setVisible(true);
        
        try{
            this.produto = cb.cadastrarProduto(telaProduto.tipo, telaProduto.resumo, telaProduto.detalhe);
            txtProduto.setText(telaProduto.tipo);
        } catch(ProdutoNaoCadastrouException e){
            JOptionPane.showMessageDialog(null, "Produto não pode ser cadastrado!");
        } catch (UsuarioNaoCadastrouException ex) {
            JOptionPane.showMessageDialog(null, "Erro no usuario!");
        } catch (LoginFalhouException ex) {
            JOptionPane.showMessageDialog(null, "Erro no Login!");
        }
        
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void btnCadastrarLeilaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarLeilaoActionPerformed
        // TODO add your handling code here:
        double preco = Double.parseDouble(lblPreco.getText());
        double incremento = Double.parseDouble(lblIncremento.getText());
        
        if(this.optLeilao == 1){
            try {
                cb.cadastrarLeilaoManual(this.produto, preco, incremento);
            } catch (UsuarioNaoCadastrouException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar!");
            } catch (LoginFalhouException ex) {
                JOptionPane.showMessageDialog(null, "Erro no Login!");
            } catch (ProdutoNaoCadastrouException ex) {
                JOptionPane.showMessageDialog(null, "Erro no produto!");
            } catch (LeilaoNaoCadastrouException ex) {
                JOptionPane.showMessageDialog(null, "Leilão não pode ser cadastrado... Tente novamente!");
            }
        } else if(this.optLeilao == 2){
            try {
                cb.cadastrarLeilaoAutomatico(this.produto, preco, incremento, Calendar.getInstance().getTime(), Calendar.getInstance().getTime());
            } catch (UsuarioNaoCadastrouException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar!");
            } catch (LoginFalhouException ex) {
                JOptionPane.showMessageDialog(null, "Erro no Login!");
            } catch (ProdutoNaoCadastrouException ex) {
                JOptionPane.showMessageDialog(null, "Erro no produto!");
            } catch (LeilaoNaoCadastrouException ex) {
                JOptionPane.showMessageDialog(null, "Leilão não pode ser cadastrado... Tente novamente!");
            }
        }else if(this.optLeilao == 3){
            try {
                cb.cadastrarLeilaoAutomaticoFechado(produto, preco, incremento, Calendar.getInstance().getTime(), Calendar.getInstance().getTime());
            } catch (UsuarioNaoCadastrouException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar!");
            } catch (LoginFalhouException ex) {
                JOptionPane.showMessageDialog(null, "Erro no Login!");
            } catch (ProdutoNaoCadastrouException ex) {
                JOptionPane.showMessageDialog(null, "Erro no produto!");
            } catch (LeilaoNaoCadastrouException ex) {
                JOptionPane.showMessageDialog(null, "Leilão não pode ser cadastrado... Tente novamente!");                
            } 
        } else{
            JOptionPane.showMessageDialog(null, "Escolha um tipo de Leilão...");
                
        }
    }//GEN-LAST:event_btnCadastrarLeilaoActionPerformed

    private void btnHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHorarioActionPerformed

    private void lblIncrementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblIncrementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIncrementoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JComprar;
    private javax.swing.JPanel JMain;
    private javax.swing.JPanel JMeusLeiloes;
    private javax.swing.JPanel JVender;
    private javax.swing.JPanel NaveBar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrarLeilao;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnHorario;
    private javax.swing.JButton btnLeiloes;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVender;
    private javax.swing.JComboBox<String> cmbLeilao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lblIncremento;
    private javax.swing.JTextField lblPreco;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JLabel txtProduto;
    // End of variables declaration//GEN-END:variables
}
